FROM node:22-alpine

WORKDIR /app

COPY package*.json turbo.json meta.json ./
COPY packages ./packages

COPY /apps/user-app ./apps/user-app
RUN npm install
RUN npx turbo db:generate

RUN cd packages/ui && npm run build
RUN npm run build-user-app
EXPOSE 3000

CMD [ "npm", "run", "start-user-app" ]


