name: CI
on:
    pull_request:
      branches:
        - main

jobs:
  turbo-repo-build-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node Environment
        uses: actions/setup-node@v4
        with:
            node-version: 22
      - name: Install Dependencies
        run: npm install

      - name: Generate Prisma Client
        run: npx turbo db:generate
      
      - name: Build the Application
        run: npm run build
      
      
